//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trending.RecordServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecordServiceRef.IRecordService")]
    public interface IRecordService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecordService/GetCurrent", ReplyAction="http://tempuri.org/IRecordService/GetCurrentResponse")]
        System.Collections.Generic.Dictionary<string, double> GetCurrent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecordService/GetCurrent", ReplyAction="http://tempuri.org/IRecordService/GetCurrentResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, double>> GetCurrentAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecordServiceChannel : Trending.RecordServiceRef.IRecordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecordServiceClient : System.ServiceModel.ClientBase<Trending.RecordServiceRef.IRecordService>, Trending.RecordServiceRef.IRecordService {
        
        public RecordServiceClient() {
        }
        
        public RecordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, double> GetCurrent() {
            return base.Channel.GetCurrent();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, double>> GetCurrentAsync() {
            return base.Channel.GetCurrentAsync();
        }
    }
}
